version: '3.9'

services:
  api:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./assets:/app/assets

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FastAPI-Pattern
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d FastAPI-Pattern" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
