"""Update user model structure

Revision ID: 004e8e088cae
Revises: 5f9a949f56cc
Create Date: 2025-03-01 11:59:09.768134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '004e8e088cae'
down_revision: Union[str, None] = '5f9a949f56cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patronymic', sa.String(length=50), default="testPatronymic"))
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('gender', postgresql.ENUM('male', 'female', name='gender'), autoincrement=False,
                                     nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'patronymic')
    # ### end Alembic commands ###
