"""Add role to user model

Revision ID: 0ba88030a47b
Revises: 91ae6262b002
Create Date: 2025-03-01 14:25:35.645664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ba88030a47b'
down_revision: Union[str, None] = '91ae6262b002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sellers', 'about',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.add_column('users', sa.Column('role', sa.Enum('buyer', 'self_employed', 'individual_entrepreneur', 'organization', name='role'), nullable=True))
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'role')
    op.alter_column('sellers', 'about',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
