"""Update sellers model

Revision ID: 57925a5f8d4d
Revises: 43a5965c134e
Create Date: 2025-03-01 21:21:19.196013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57925a5f8d4d'
down_revision: Union[str, None] = '43a5965c134e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('passport_series', sa.Integer(), nullable=True))
    op.add_column('sellers', sa.Column('passport_number', sa.Integer(), nullable=True))
    op.add_column('sellers', sa.Column('birthday_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'birthday_date')
    op.drop_column('sellers', 'passport_number')
    op.drop_column('sellers', 'passport_series')
    # ### end Alembic commands ###
