"""Del short_name column

Revision ID: 5b6e682bec77
Revises: 35a179c79ea8
Create Date: 2024-11-28 15:52:10.086225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6e682bec77'
down_revision: Union[str, None] = '35a179c79ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_short_name_key', 'users', type_='unique')
    op.drop_column('users', 'short_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_short_name_key', 'users', ['short_name'])
    # ### end Alembic commands ###
