"""Update seller model

Revision ID: 91ae6262b002
Revises: d72fa107e72d
Create Date: 2025-03-01 12:28:01.626936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ae6262b002'
down_revision: Union[str, None] = 'd72fa107e72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('sellers', sa.Column('surname', sa.String(length=50), nullable=False))
    op.add_column('sellers', sa.Column('patronymic', sa.String(length=50), nullable=False))
    op.add_column('sellers', sa.Column('about', sa.String(length=1000), nullable=False))
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(length=50),)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('sellers', 'about')
    op.drop_column('sellers', 'patronymic')
    op.drop_column('sellers', 'surname')
    op.drop_column('sellers', 'name')
    # ### end Alembic commands ###
