"""Add is_confirmed to transaction model

Revision ID: abae54f22990
Revises: fac0b733db27
Create Date: 2025-03-01 22:48:57.192359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abae54f22990'
down_revision: Union[str, None] = 'fac0b733db27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_confirmed')
    # ### end Alembic commands ###
