"""Create Seller model

Revision ID: d72fa107e72d
Revises: 004e8e088cae
Create Date: 2025-03-01 12:15:11.068627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72fa107e72d'
down_revision: Union[str, None] = '004e8e088cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('inn', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('self_employed', 'individual_entrepreneur', 'organization', name='role'), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('inn')
    )
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(length=50),)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sellers')
    # ### end Alembic commands ###
