"""Edit seller_inn type in transaction model

Revision ID: f8e093347f5a
Revises: 57925a5f8d4d
Create Date: 2025-03-01 22:05:15.105636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e093347f5a'
down_revision: Union[str, None] = '57925a5f8d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
