"""Add idempotency_key

Revision ID: fac0b733db27
Revises: f8e093347f5a
Create Date: 2025-03-01 22:43:07.315064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac0b733db27'
down_revision: Union[str, None] = 'f8e093347f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'idempotency_key')
    # ### end Alembic commands ###
